version: "3.9"

services:
  frontend-dev:
    build:
      context: .
      target: dev      # Usa la etapa "dev" del Dockerfile
    container_name: bingo-board-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app                  # Monta tu cÃ³digo local
      - /app/node_modules       # Evita sobrescribir node_modules
    profiles:
      - dev

  frontend-prod:
    build:
      context: .
      target: prod     # Usa la etapa "prod" del Dockerfile (Nginx)
    container_name: bingo-board-prod
    ports:
      - "8081:80"      # Externo 8081 -> Nginx 80
    environment:
      - NODE_ENV=production
    profiles:
      - prod
